[package]
name = "raxolotl"
version = "0.0.1"
authors = ["harrison <notallama@gmail.com>"]
links = "curve25519-donna"
build = "build.rs"



[build-dependencies]
gcc = "0.3"

[dependencies]
rustc-serialize = "0.3"
rand = "*"

[dev-dependencies]
protobuf = "1.0.0"
rust-crypto = "*"

